version: "3"
services:
  application:
    image: spring-boot-mysql-app
    ports:
      - "8080:2525"
    networks:
      - niranjana-network
    depends_on:
      - mysqldb
    
  mysqldb:
    image: mysql:8.5
    networks:
      - niranjana-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projecteidiko
networks:
  niranjana-network: